import type { RuntimeAttempt } from "./types";

const now = new Date("2026-07-31T01:50:00.000Z");
const startsAt = new Date(now.getTime() + 10 * 60 * 1000);
const endsAt = new Date(startsAt.getTime() + 45 * 60 * 1000);

export const mockRuntimeAttempt: RuntimeAttempt = {
  session: {
    attemptId: "mock-attempt-001",
    quizId: "quiz-civil-service-2026",
    assessmentTitle: "Төрийн албан хаагчийн ерөнхий мэдлэгийн үнэлгээ",
    userId: "candidate-001",
    userDisplayName: "Бат-Эрдэнэ Б.",
    serverNow: now.toISOString(),
    startsAt: startsAt.toISOString(),
    endsAt: endsAt.toISOString(),
    durationSeconds: 45 * 60,
    status: "waiting",
    autosaveIntervalSeconds: 5,
    heartbeatIntervalSeconds: 5,
    encryptedPayload: {
      payloadId: "payload-mock-attempt-001",
      quizId: "quiz-civil-service-2026",
      attemptId: "mock-attempt-001",
      algorithm: "AES-GCM",
      keyDelivery: "start_unlock_event",
      encryptedContent: "mock.encrypted.payload",
      iv: "mock-iv",
      checksum: "sha256:mock-checksum",
      createdAt: now.toISOString(),
    },
    manifest: [
      {
        id: "q1",
        code: "Q1",
        type: "single_choice",
        sectionId: "sec-general",
        sectionName: "Ерөнхий мэдлэг",
        order: 1,
        points: 2,
        required: true,
      },
      {
        id: "q2",
        code: "Q2",
        type: "multiple_choice",
        sectionId: "sec-general",
        sectionName: "Ерөнхий мэдлэг",
        order: 2,
        points: 3,
        required: true,
      },
      {
        id: "q3",
        code: "Q3",
        type: "essay",
        sectionId: "sec-application",
        sectionName: "Хэрэглээ",
        order: 3,
        points: 10,
        required: true,
      },
    ],
    proctoringPolicy: {
      requireFullscreen: true,
      warnOnVisibilityChange: true,
      warnOnWindowBlur: true,
      disableCopyPaste: true,
      disableContextMenu: true,
      maxWarningsBeforeLock: 3,
      lockOnViolation: true,
    },
    resultVisibilityPolicy: {
      hideSolutions: true,
      showLeaderboard: false,
      showScore: true,
      showCorrectness: false,
      showCorrectAnswers: false,
      showExplanations: false,
      resultReleaseMode: "after_close",
    },
  },
  snapshot: {
    attemptId: "mock-attempt-001",
    answers: {},
    markedForReview: {},
    localVersion: 0,
    serverVersion: 0,
    pendingSubmit: false,
  },
  questions: [
    {
      id: "q1",
      code: "Q1",
      prompt: "Монгол Улсын Үндсэн хуулийн үндсэн зарчимд аль нь хамаарах вэ?",
      instruction: "Нэг зөв хариулт сонгоно уу.",
      type: "single_choice",
      points: 2,
      options: [
        { id: "a", label: "Ардчилсан ёс" },
        { id: "b", label: "Зөвхөн эдийн засгийн өсөлт" },
        { id: "c", label: "Нууц захиргаа" },
        { id: "d", label: "Хувийн ашиг сонирхол" },
      ],
    },
    {
      id: "q2",
      code: "Q2",
      prompt: "Төрийн үйлчилгээний чанарыг сайжруулахад нөлөөлөх хүчин зүйлсийг сонго.",
      instruction: "Нийт хамаарах хариултыг сонгоно уу.",
      type: "multiple_choice",
      points: 3,
      options: [
        { id: "a", label: "Ил тод байдал" },
        { id: "b", label: "Хариуцлага" },
        { id: "c", label: "Иргэн төвтэй үйлчилгээ" },
        { id: "d", label: "Мэдээллийг зориуд нуух" },
      ],
    },
    {
      id: "q3",
      code: "Q3",
      prompt:
        "Иргэн үйлчилгээ авах явцад олон шат дамжлага үүсэж байгаа нөхцөлд сайжруулах саналаа тайлбарлана уу.",
      instruction: "Бүтэцтэй, үндэслэлтэй хариулт бичнэ үү.",
      type: "essay",
      points: 10,
    },
  ],
};
