import type { ProfileMockData } from "./types";

export const mockProfile: ProfileMockData = {
  identity: {
    fullName: "Баттуяа Мөнхцэцэг",
    registryNumber: "U-2024-001245",
    email: "m.battuya@example.com",
    phone: "9922-1234",
    birthDate: "1990-05-15",
    nationalId: "УБ90051532",
    gender: "Эмэгтэй",
    citizenship: "Монгол",
    country: "Монгол",
    address: "Улаанбаатар хот, Сүхбаатар дүүрэг, 1-р хороо",
    education: "Магистр",
    profession: "Боловсрол судлаач",
    workArea: "Багш, Сургалтын менежмент",
    preferredRole: "Candidate, Assessor",
    registeredAt: "2024-02-20 14:35",
    lastUpdatedAt: "2024-05-19 10:22",
  },
  verificationLevel: 45,
  verificationItems: [
    {
      id: "identity",
      title: "Хувийн мэдээлэл",
      description: "Иргэний үнэмлэх, төрсөн он сар өдөр зэрэг",
      status: "pending",
    },
    {
      id: "employment",
      title: "Албан тушаал",
      description: "Одоогийн албан тушаалаа баталгаажуулах",
      status: "not_requested",
    },
    {
      id: "organisation",
      title: "Байгууллагын харьяалал",
      description: "Ажиллаж буй байгууллагаа баталгаажуулах",
      status: "verified",
    },
    {
      id: "education",
      title: "Боловсролын зэрэг",
      description: "Диплом, зэрэг, сургуулийг баталгаажуулах",
      status: "not_requested",
    },
    {
      id: "assessor",
      title: "Мэргэжлийн үнэлгээ",
      description: "Мэргэжлийн үнэлэгчээр баталгаажуулах",
      status: "rejected",
    },
  ],
  employmentHistory: [
    {
      id: "job-1",
      position: "Сургалтын менежер",
      organisation: "Боловсрол Инноваци ХХК",
      startDate: "2023-06-01",
      endDate: "Одоо хүртэл",
      status: "active",
    },
    {
      id: "job-2",
      position: "Багш",
      organisation: "Шинэ Монгол сургууль",
      startDate: "2018-09-01",
      endDate: "2023-05-31",
      status: "expired",
    },
    {
      id: "job-3",
      position: "Сургалтын зохицуулагч",
      organisation: "Боловсрол тешвин ТББ",
      startDate: "2016-03-10",
      endDate: "2018-08-31",
      status: "expired",
    },
  ],
  affiliations: [
    {
      id: "aff-1",
      organisation: "Боловсрол Инноваци ХХК",
      unit: "Сургалтын хэлтэс",
      role: "Organisation Admin",
      verifiedBy: "Platform Reviewer",
      status: "active",
    },
    {
      id: "aff-2",
      organisation: "Шинэ Монгол сургууль",
      unit: "Математикийн тэнхим",
      role: "Assessor",
      verifiedBy: "Хүсэлт хянагдаж байна",
      status: "pending",
    },
    {
      id: "aff-3",
      organisation: "Ирээдүй коллеж",
      unit: "Ерөнхий эрдмийн тэнхим",
      role: "Reviewer",
      verifiedBy: "Expired",
      status: "expired",
    },
  ],
  documents: [
    {
      id: "doc-1",
      name: "Иргэний үнэмлэх.pdf",
      type: "Identity",
      uploadedAt: "2024-05-01",
      expiryDate: "2030-05-01",
      visibility: "reviewer",
      status: "pending",
    },
    {
      id: "doc-2",
      name: "Диплом.pdf",
      type: "Education",
      uploadedAt: "2024-04-21",
      expiryDate: "Хугацаагүй",
      visibility: "private",
      status: "not_requested",
    },
    {
      id: "doc-3",
      name: "Ажлын тодорхойлолт.docx",
      type: "Employment",
      uploadedAt: "2024-05-12",
      expiryDate: "2025-05-12",
      visibility: "organisation",
      status: "verified",
    },
  ],
  security: {
    mfaEnabled: false,
    passwordUpdatedAt: "2024-05-18",
    sessions: [
      {
        id: "session-1",
        device: "Chrome on Windows",
        location: "Ulaanbaatar, Mongolia",
        lastActiveAt: "Одоо идэвхтэй",
        current: true,
      },
      {
        id: "session-2",
        device: "Safari on iPhone",
        location: "Ulaanbaatar, Mongolia",
        lastActiveAt: "2024-05-17 21:14",
      },
    ],
  },
};
