'use client';
import {useEffect,useState} from 'react';
import {Button,Input} from '@seek/ui';
import {questionTypeLabels} from '@/features/assessor-workspace/mock-data';
import {RoleGuard} from '@/components/auth/role-guard';
import {useI18n} from '@/i18n/use-t';
import {ReviewDetail,reviewJson,questionUrl} from '@/features/question-review/review';
export default function QuestionReviewPage(){
 const {t}=useI18n();const [rows,setRows]=useState<any[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState('IN_REVIEW'),[type,setType]=useState(''),[search,setSearch]=useState(''),[context,setContext]=useState(''),[owner,setOwner]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[contexts,setContexts]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true;Promise.all([reviewJson(questionUrl+'/metadata/assessment-contexts'),reviewJson('/api/v1/auth/admin/users')]).then(([cs,us])=>{if(active){setContexts(cs);setUsers(us);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{setLoading(true);setError('');reviewJson(questionUrl+'?'+new URLSearchParams({review:'true',status,type,search,assessmentContextId:context,ownerUserId:owner,from,to,page:String(page)})).then(d=>{if(active){setRows(d.items);setTotal(d.total);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});},200);return()=>{active=false;clearTimeout(timer);};},[status,type,search,context,owner,from,to,page,refresh]);
 const reset=(fn:()=>void)=>{fn();setPage(1);};
 return <RoleGuard allowedRoles={['super_admin']}><div className="space-y-5 min-w-0"><h1 className="text-2xl font-semibold">{t('review.title')}</h1>
 <div className="flex flex-wrap gap-3"><select aria-label={t('review.status')} className="border rounded p-2" value={status} onChange={e=>reset(()=>setStatus(e.target.value))}>{['ALL','DRAFT','IN_REVIEW','CHANGES_REQUESTED','APPROVED','PUBLISHED','REJECTED','RETIRED'].map(s=><option key={s} value={s}>{t(('review.'+s) as any)}</option>)}</select><select aria-label={t('review.type')} className="border rounded p-2 max-w-full" value={type} onChange={e=>reset(()=>setType(e.target.value))}><option value="">{t('review.type')}</option>{Object.entries(questionTypeLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><Input aria-label={t('review.search')} placeholder={t('review.search')} value={search} onChange={e=>reset(()=>setSearch(e.target.value))}/><select aria-label={t('review.context')} className="border rounded p-2 max-w-full" value={context} onChange={e=>reset(()=>setContext(e.target.value))}><option value="">{t('review.context')}</option>{contexts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label={t('review.author')} className="border rounded p-2 max-w-full" value={owner} onChange={e=>reset(()=>setOwner(e.target.value))}><option value="">{t('review.author')}</option>{users.map(u=><option key={u.id} value={u.id}>{u.email}</option>)}</select><label>{t('review.from')}<input className="border rounded p-2" type="date" value={from} onChange={e=>reset(()=>setFrom(e.target.value))}/></label><label>{t('review.to')}<input className="border rounded p-2" type="date" value={to} onChange={e=>reset(()=>setTo(e.target.value))}/></label><Button onClick={()=>setRefresh(x=>x+1)}>{t('context.retry')}</Button></div>
 {error&&<p role="alert" className="text-danger">{error}</p>}
 {loading?<p role="status">{t('access.loading')}</p>:<><p>{total} {t('review.items')}</p>{!rows.length&&<p>{t('review.empty')}</p>}<div className="grid gap-3">{rows.map(q=><button type="button" key={q.id} className={'text-left rounded border p-4 '+(selected===q.id?'border-primary bg-muted-background':'border-border bg-surface')} onClick={()=>setSelected(q.id)}><strong>{q.code} — {q.versions[0]?.title}</strong><p>{users.find(u=>u.id===q.ownerUserId)?.email||q.ownerUserId} · v{q.versions[0]?.versionNumber} · {t(('review.'+q.versions[0]?.versionStatus) as any)} · {new Date(q.updatedAt).toLocaleString()}</p></button>)}</div><div className="flex gap-3"><Button disabled={page===1} onClick={()=>setPage(x=>x-1)}>←</Button><span>{page}</span><Button disabled={page*20>=total} onClick={()=>setPage(x=>x+1)}>→</Button></div></>}
 {selected&&<ReviewDetail key={selected} id={selected} onChanged={()=>setRefresh(x=>x+1)}/>}</div></RoleGuard>;
}
