"use client";
import {useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {authFetch} from '@/lib/auth-client';
import {Button,Card} from '@seek/ui';
export default function CandidateAssessments(){
 const search=useSearchParams();
 const [schedules,setSchedules]=useState<any[]>([]),[quizzes,setQuizzes]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function api(path:string,method='GET',body?:unknown){const r=await authFetch('/api/v1/'+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.message||'Алдаа гарлаа.');return d;}
 async function load(){try{const [s,q,u]=await Promise.all([api('assessment/schedules'),api('assessment/quizzes'),api('auth/admin/users')]);setSchedules(s);setQuizzes(q);setUsers(u.filter((x:any)=>x.roles?.includes('CANDIDATE')));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);useEffect(()=>{if(selected)api('assessment/candidate/admin/assignments/'+selected).then(setAssignments).catch(e=>setError(e.message));},[selected]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await api('assessment/schedules','POST',{name:f.get('name'),code:f.get('code'),quizRevisionId:f.get('revision'),availableFrom:new Date(String(f.get('start'))).toISOString(),availableUntil:new Date(String(f.get('end'))).toISOString(),accessMode:'ASSIGNED_ONLY'});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function assign(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await api('assessment/candidate/admin/assignments/'+selected,'POST',{userId:f.get('user')});setAssignments(await api('assessment/candidate/admin/assignments/'+selected));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="p-6 space-y-6"><h1 className="text-2xl font-bold">Шалгалтын хуваарь ба оролцогчид</h1><a className="text-primary underline" href="/admin/candidate-results">Хариулт үнэлэх, дүн нийтлэх</a>{error&&<p role="alert">{error}</p>}<Card><h2 className="font-bold mb-4">Хуваарь үүсгэх</h2><form onSubmit={create} className="grid gap-3 md:grid-cols-2"><label>Нэр<input name="name" className="block w-full border rounded p-2" required/></label><label>Код<input name="code" className="block w-full border rounded p-2" required/></label><label>Нийтэлсэн quiz хувилбар<select key={quizzes.length} defaultValue={search.get("quizRevisionId")||""} name="revision" className="block w-full border rounded p-2" required><option value="">Сонгох</option>{quizzes.flatMap(q=>Array.from(new Map([...(q.revisions||[]),...(q.currentPublishedRevision?[q.currentPublishedRevision]:[])].map((r:any)=>[r.id,r])).values()).filter((r:any)=>r.revisionStatus==='PUBLISHED').map((r:any)=><option key={r.id} value={r.id}>{q.title} — v{r.revisionNumber}</option>))}</select></label><label>Эхлэх (таны төхөөрөмжийн цаг)<input type="datetime-local" name="start" className="block border rounded p-2" required/></label><label>Хаах (таны төхөөрөмжийн цаг)<input type="datetime-local" name="end" className="block border rounded p-2" required/></label><Button disabled={busy} type="submit">Хуваарь үүсгэх</Button></form></Card>
 <Card><label>Хуваарь<select aria-label="Хуваарь" value={selected} onChange={e=>setSelected(e.target.value)} className="block w-full border rounded p-2"><option value="">Сонгох</option>{schedules.map(s=><option key={s.id} value={s.id}>{s.name} ({s.status})</option>)}</select></label>{selected&&<div className="mt-4 space-y-4"><Button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api('assessment/schedules/'+selected+'/publish','POST',{});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Хуваарь нийтлэх</Button><form onSubmit={assign} className="flex flex-wrap gap-3"><label>CANDIDATE хэрэглэгч<select aria-label="CANDIDATE хэрэглэгч" name="user" required className="block border rounded p-2"><option value="">Сонгох</option>{users.map(u=><option key={u.id} value={u.id}>{u.email}</option>)}</select></label><Button type="submit" disabled={busy}>Оноох</Button></form>{assignments.map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-2"><span>{users.find(u=>u.id===a.userId)?.email||a.userId} — {a.status}</span><Button disabled={busy||a.status==='REVOKED'} onClick={async()=>{if(!window.confirm('Энэ хэрэглэгчийн шалгалтын эрхийг цуцлах уу?'))return;setBusy(true);try{await api('assessment/candidate/admin/assignments/'+a.id,'DELETE');setAssignments(await api('assessment/candidate/admin/assignments/'+selected));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Эрх цуцлах</Button></div>)}</div>}</Card></main>;
}
