import type {
  BloomLevel,
  Blueprint,
  CompetencyType,
  DifficultyLevel,
  QuestionBankItem,
  QuestionType,
  QuestionWorkflowStatus,
  Quiz,
} from "./types";

export const questionTypeLabels: Record<QuestionType, string> = {
  single_choice: "Нэг сонголт",
  multiple_choice: "Олон сонголт",
  matching: "Харгалзуулах",
  ordering: "Эрэмбэлэх",
  fill_blank: "Нөхөх",
  matrix: "Матриц",
  numeric: "Тоон хариулт",
  likert: "Likert шкал",
  sjt: "SJT",
  case_bundle: "Кейсэд суурилсан багц",
  essay: "Бичгийн шалгалт",
};

export const statusLabels: Record<QuestionWorkflowStatus, string> = {
  draft: "Ноорог",
  approval_requested: "Батлуулах хүсэлт",
  in_review: "Хянагдаж байна",
  changes_requested: "Засвар шаардлагатай",
  resubmitted: "Дахин батлуулах хүсэлт",
  approved: "Батлагдсан",
  published: "Нийтлэгдсэн",
  archived: "Архивлагдсан",
  rejected: "Татгалзсан",
  deleted: "Устгасан",
};

export const bloomLabels: Record<BloomLevel, string> = {
  remember: "Сэргээн санах",
  understand: "Ойлгох",
  apply: "Хэрэглэх",
  analyze: "Задлан шинжлэх",
  evaluate: "Үнэлэх",
  create: "Бүтээх",
};

export const competencyLabels: Record<CompetencyType, string> = {
  knowledge: "Мэдлэг",
  skill: "Ур чадвар",
  attitude: "Хандлага",
  digital: "Дижитал ур чадвар",
  professional: "Ажил мэргэжил",
};

export const difficultyLabels: Record<DifficultyLevel, string> = {
  very_easy: "Маш хялбар",
  easy: "Хялбар",
  medium: "Дунд",
  hard: "Хүнд",
  very_hard: "Маш хүнд",
};

export const topicTree = [
  { id: "algebra", label: "Шугаман алгебр" },
  { id: "fractions", label: "Энгийн бутархай" },
  { id: "communication", label: "Харилцааны ур чадвар" },
  { id: "cyber", label: "Кибер аюулгүй байдал" },
  { id: "leadership", label: "Манлайлал" },
];

const actor = {
  actorId: "mock-assessor",
  actorName: "Ассессор Б.",
  actorRole: "Assessor",
};

export const mockQuestionBank: QuestionBankItem[] = [
  {
    id: "qb-001",
    code: "MX-60",
    title: "Бутархайн тэнцүү байдал",
    stem: "2/3 * 3/4 үйлдлийг гүйцэтгэхэд хамгийн хялбар хэлбэрт шилжүүлнэ үү.",
    type: "single_choice",
    status: "published",
    points: 2,
    durationSeconds: 60,
    bloomLevel: "apply",
    competencyType: "knowledge",
    topicId: "fractions",
    topicName: "Энгийн бутархай",
    difficulty: "easy",
    tags: ["бутархай", "үржих"],
    options: [
      { id: "a", label: "A", content: "1/2", isCorrect: true },
      { id: "b", label: "B", content: "6/12" },
      { id: "c", label: "C", content: "8/9" },
      { id: "d", label: "D", content: "5/7" },
    ],
    answerKey: "A",
    rubric: "Зөв сонголт 2 оноо.",
    feedback: "2/3 болон 3/4-ийг үржүүлээд 6/12, хялбаршуулбал 1/2 болно.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-20 09:30",
    updatedAt: "2026-07-28 12:10",
    workflowHistory: [
      {
        id: "w-001",
        status: "published",
        comment: "Үндсэн тестийн санд нийтэлсэн.",
        createdAt: "2026-07-28 12:10",
        ...actor,
      },
    ],
  },
  {
    id: "qb-002",
    code: "MX-59",
    title: "Үйлдийн чанарыг ангилах",
    stem: "a + b = b + a илэрхийлэл ямар хуультай тохирох вэ?",
    type: "matching",
    status: "approved",
    points: 3,
    durationSeconds: 90,
    bloomLevel: "understand",
    competencyType: "knowledge",
    topicId: "algebra",
    topicName: "Шугаман алгебр",
    difficulty: "medium",
    tags: ["хууль", "алгебр"],
    options: [
      { id: "a", label: "A", content: "Нэмэхийн байр солих хууль", isCorrect: true },
      { id: "b", label: "B", content: "Нэмэхийн бүлэглэх хууль" },
      { id: "c", label: "C", content: "Үржихийн нэмэхэд тархах хууль" },
    ],
    answerKey: "A",
    rubric: "Зөв харгалзуулалт бүр 1 оноо.",
    feedback: "Нэмэгдэхүүний байр солигдоход нийлбэр өөрчлөгдөхгүй.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Reviewer Т.",
    createdAt: "2026-07-19 11:00",
    updatedAt: "2026-07-27 16:20",
    workflowHistory: [
      {
        id: "w-002",
        status: "approved",
        comment: "Контент болон зөв хариулт баталгаажсан.",
        actorId: "mock-reviewer",
        actorName: "Reviewer Т.",
        actorRole: "Reviewer",
        createdAt: "2026-07-27 16:20",
      },
    ],
  },
  {
    id: "qb-003",
    code: "CS-21",
    title: "Харилцааны нөхцөл байдлын шийдвэр",
    stem: "Иргэн бухимдсан үед хамгийн түрүүнд ямар хариу үйлдэл үзүүлэх вэ?",
    type: "sjt",
    status: "changes_requested",
    points: 4,
    durationSeconds: 120,
    bloomLevel: "evaluate",
    competencyType: "attitude",
    topicId: "communication",
    topicName: "Харилцааны ур чадвар",
    difficulty: "hard",
    tags: ["SJT", "иргэн"],
    options: [
      { id: "a", label: "A", content: "Тайван сонсож, асуудлыг тодруулна.", score: 4 },
      { id: "b", label: "B", content: "Журам тайлбарлаад шууд дуусгана.", score: 1 },
      { id: "c", label: "C", content: "Дараагийн ажилтанд шилжүүлнэ.", score: 2 },
    ],
    answerKey: "A",
    rubric: "Нөхцөл байдлын оноо 1-4 хооронд.",
    feedback: "Эхний алхам нь сэтгэл хөдлөлийг намжаах сонсох үйлдэл байна.",
    media: [{ type: "audio", name: "Иргэний дуудлага.mp3", url: "#" }],
    createdBy: "Ассессор Б.",
    updatedBy: "Reviewer Т.",
    createdAt: "2026-07-18 10:00",
    updatedAt: "2026-07-26 15:30",
    workflowHistory: [
      {
        id: "w-003",
        status: "changes_requested",
        comment: "Хоёр дахь сонголтын онооны тайлбарыг тодруулах шаардлагатай.",
        actorId: "mock-reviewer",
        actorName: "Reviewer Т.",
        actorRole: "Reviewer",
        createdAt: "2026-07-26 15:30",
      },
    ],
  },
  {
    id: "qb-004",
    code: "DG-12",
    title: "Файлтай даалгавар",
    stem: "Хавсаргасан хүснэгтийг уншаад хамгийн эрсдэлтэй үзүүлэлтийг тайлбарлана уу.",
    type: "essay",
    status: "draft",
    points: 5,
    durationSeconds: 300,
    bloomLevel: "analyze",
    competencyType: "digital",
    topicId: "cyber",
    topicName: "Кибер аюулгүй байдал",
    difficulty: "medium",
    tags: ["файл", "шинжилгээ"],
    options: [],
    answerKey: "Rubric based",
    rubric: "Асуудал тодорхойлох 2, нотолгоо 2, зөвлөмж 1.",
    feedback: "Өгөгдөл дээр тулгуурласан тайлбар шаардлагатай.",
    media: [{ type: "file", name: "risk-matrix.xlsx", url: "#" }],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-25 09:00",
    updatedAt: "2026-07-25 09:00",
    workflowHistory: [
      {
        id: "w-004",
        status: "draft",
        comment: "Эхний ноорог үүсгэсэн.",
        createdAt: "2026-07-25 09:00",
        ...actor,
      },
    ],
  },
  {
    id: "qb-005",
    code: "MX-58",
    title: "Рационал илэрхийлэл хялбарчлах",
    stem:
      "Дараах илэрхийллийг хялбарчил: $\\frac{x-1}{x^2-1}=?$\n\n|№|асуулт|\n|---|---|\n|1|Хуваарийг үржигдэхүүн болгон задла.|\n|2|Ижил үржигдэхүүнийг хураа.|",
    type: "multiple_choice",
    status: "published",
    points: 3,
    durationSeconds: 90,
    bloomLevel: "apply",
    competencyType: "knowledge",
    topicId: "algebra",
    topicName: "Шугаман алгебр",
    difficulty: "medium",
    tags: ["олон сонголт", "томъёо"],
    options: [
      { id: "a", label: "A", content: "$\\frac{1}{x+1}$", isCorrect: true },
      { id: "b", label: "B", content: "$\\frac{1}{x-1}$" },
      { id: "c", label: "C", content: "$x-1$" },
      { id: "d", label: "D", content: "$x+1$" },
    ],
    answerKey: "A",
    rubric: "Зөв хялбаршуулсан хэлбэр 3 оноо.",
    feedback: "$x^2-1=(x-1)(x+1)$ тул $x-1$ хураагдаж $\\frac{1}{x+1}$ үлдэнэ.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-25 10:00",
    updatedAt: "2026-07-29 10:00",
    workflowHistory: [
      {
        id: "w-005",
        status: "published",
        comment: "KaTeX томъёотой олон сонголтын жишээ нэмсэн.",
        createdAt: "2026-07-29 10:00",
        ...actor,
      },
    ],
  },
  {
    id: "qb-006",
    code: "OR-21",
    title: "Бутархайг өсөхөөр эрэмбэлэх",
    stem: "Дараах бутархайнуудыг багаас их рүү зөв дарааллаар байрлуул.",
    type: "ordering",
    status: "approved",
    points: 4,
    durationSeconds: 120,
    bloomLevel: "analyze",
    competencyType: "knowledge",
    topicId: "fractions",
    topicName: "Энгийн бутархай",
    difficulty: "medium",
    tags: ["эрэмбэлэх", "бутархай"],
    options: [
      { id: "a", label: "1", content: "1/8" },
      { id: "b", label: "2", content: "1/4" },
      { id: "c", label: "3", content: "1/2" },
      { id: "d", label: "4", content: "3/4" },
    ],
    answerKey: "1/8 → 1/4 → 1/2 → 3/4",
    rubric: "Бүрэн зөв дараалал 4 оноо.",
    feedback: "Ижил хуваарьт шилжүүлж харьцуулбал дараалал тодорхой болно.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Reviewer Т.",
    createdAt: "2026-07-22 14:00",
    updatedAt: "2026-07-27 09:15",
    workflowHistory: [
      {
        id: "w-006",
        status: "approved",
        comment: "Эрэмбэлэх даалгавар батлагдсан.",
        actorId: "mock-reviewer",
        actorName: "Reviewer Т.",
        actorRole: "Reviewer",
        createdAt: "2026-07-27 09:15",
      },
    ],
  },
  {
    id: "qb-007",
    code: "FI-50",
    title: "Хоосон зай нөхөх",
    stem: "3/5 бутархайг хуваарь нь 15 байх бутархай болгон өргөтгөвөл хүртвэр нь ___ болно.",
    type: "fill_blank",
    status: "approval_requested",
    points: 3,
    durationSeconds: 90,
    bloomLevel: "apply",
    competencyType: "knowledge",
    topicId: "fractions",
    topicName: "Энгийн бутархай",
    difficulty: "easy",
    tags: ["нөхөх", "бутархай"],
    options: [],
    answerKey: "9",
    rubric: "Зөв тоон утга 3 оноо.",
    feedback: "Хуваарийг 15 болгохын тулд 5-ыг 3-аар үржүүлнэ, хүртвэрийг мөн 3-аар үржүүлнэ.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-23 11:20",
    updatedAt: "2026-07-28 11:20",
    workflowHistory: [
      {
        id: "w-007",
        status: "approval_requested",
        comment: "Батлуулах хүсэлт илгээсэн.",
        createdAt: "2026-07-28 11:20",
        ...actor,
      },
    ],
  },
  {
    id: "qb-008",
    code: "MT-14",
    title: "Аравтын ба энгийн бутархайг харьцуулах",
    stem: "Дараах хосууд хоорондоо тэнцүү эсэхийг тэмдэглэ.",
    type: "matrix",
    status: "in_review",
    points: 3,
    durationSeconds: 120,
    bloomLevel: "understand",
    competencyType: "knowledge",
    topicId: "fractions",
    topicName: "Энгийн бутархай",
    difficulty: "medium",
    tags: ["матриц", "харьцуулах"],
    options: [
      { id: "a", label: "3/10 ба 0.3", content: "Тэнцүү", isCorrect: true },
      { id: "b", label: "1/4 ба 0.25", content: "Тэнцүү", isCorrect: true },
      { id: "c", label: "2/5 ба 0.45", content: "Тэнцүү биш", isCorrect: true },
    ],
    answerKey: "Тэнцүү, тэнцүү, тэнцүү биш",
    rubric: "Мөр бүр 1 оноо.",
    feedback: "Энгийн бутархайг аравтын бутархайд шилжүүлж шалгана.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Reviewer Т.",
    createdAt: "2026-07-24 09:45",
    updatedAt: "2026-07-29 09:45",
    workflowHistory: [
      {
        id: "w-008",
        status: "in_review",
        comment: "Матриц даалгаврыг reviewer шалгаж байна.",
        actorId: "mock-reviewer",
        actorName: "Reviewer Т.",
        actorRole: "Reviewer",
        createdAt: "2026-07-29 09:45",
      },
    ],
  },
  {
    id: "qb-009",
    code: "NM-07",
    title: "Тоон хариулт",
    stem: "$12 \\div 0.5$ үйлдлийн утгыг тоогоор бич.",
    type: "numeric",
    status: "draft",
    points: 2,
    durationSeconds: 60,
    bloomLevel: "remember",
    competencyType: "knowledge",
    topicId: "algebra",
    topicName: "Шугаман алгебр",
    difficulty: "very_easy",
    tags: ["тоон хариулт", "katex"],
    options: [],
    answerKey: "24",
    rubric: "Зөв тоон утга 2 оноо.",
    feedback: "0.5-аар хуваах нь 2-оор үржүүлэхтэй адил.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-26 08:30",
    updatedAt: "2026-07-26 08:30",
    workflowHistory: [
      {
        id: "w-009",
        status: "draft",
        comment: "Тоон хариултын ноорог.",
        createdAt: "2026-07-26 08:30",
        ...actor,
      },
    ],
  },
  {
    id: "qb-010",
    code: "LK-03",
    title: "Суралцах хандлагын Likert шкал",
    stem: "Би шинэ мэдлэгийг өдөр тутмын ажилдаа хэрэглэхийг хичээдэг.",
    type: "likert",
    status: "published",
    points: 5,
    durationSeconds: 45,
    bloomLevel: "evaluate",
    competencyType: "attitude",
    topicId: "communication",
    topicName: "Харилцааны ур чадвар",
    difficulty: "easy",
    tags: ["likert", "хандлага"],
    options: [
      { id: "a", label: "1", content: "Огт санал нийлэхгүй" },
      { id: "b", label: "2", content: "Санал нийлэхгүй" },
      { id: "c", label: "3", content: "Дунд зэрэг" },
      { id: "d", label: "4", content: "Санал нийлнэ" },
      { id: "e", label: "5", content: "Бүрэн санал нийлнэ", isCorrect: true },
    ],
    answerKey: "1-5 шкал",
    rubric: "Likert шкалын оноолол 1-5.",
    feedback: "Хандлагын үнэлгээнд зөв/буруу бус шкалын оноо хэрэглэнэ.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-21 13:00",
    updatedAt: "2026-07-30 13:00",
    workflowHistory: [
      {
        id: "w-010",
        status: "published",
        comment: "Likert шкал нийтлэгдсэн.",
        createdAt: "2026-07-30 13:00",
        ...actor,
      },
    ],
  },
  {
    id: "qb-011",
    code: "CB-09",
    title: "Кейсэд суурилсан багц",
    stem: "Доорх байгууллагын сургалтын кейсийг уншаад дараах дэд асуултуудад хариул.",
    type: "case_bundle",
    status: "archived",
    points: 8,
    durationSeconds: 480,
    bloomLevel: "analyze",
    competencyType: "professional",
    topicId: "leadership",
    topicName: "Манлайлал",
    difficulty: "hard",
    tags: ["кейс", "манлайлал"],
    options: [
      { id: "a", label: "Дэд асуулт 1", content: "Гол эрсдэлийг тодорхойл." },
      { id: "b", label: "Дэд асуулт 2", content: "Сайжруулах эхний алхмыг сонго." },
      { id: "c", label: "Дэд асуулт 3", content: "Хэрэгжилтийн шалгуур үзүүлэлт бич." },
    ],
    answerKey: "Rubric based bundle",
    rubric: "Кейс ойлголт 3, шийдэл 3, хэмжүүр 2.",
    feedback: "Кейсийн нотолгоонд тулгуурласан хариулт шаардлагатай.",
    media: [{ type: "video", name: "case-brief.mp4", url: "#" }],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-15 16:00",
    updatedAt: "2026-07-25 16:00",
    workflowHistory: [
      {
        id: "w-011",
        status: "archived",
        comment: "Хуучин кейсийн хувилбарыг архивлав.",
        createdAt: "2026-07-25 16:00",
        ...actor,
      },
    ],
  },
];

export const mockBlueprints: Blueprint[] = [
  {
    id: "bp-fractions-core",
    title: "Бутархайн суурь чадвар",
    description: "Энгийн бутархайн ойлголт, үйлдэл, хэрэглээний тэнцвэртэй blueprint.",
    topicId: "fractions",
    topicName: "Энгийн бутархай",
    passScore: 73,
    totalDurationMinutes: 24,
    status: "ready",
    updatedAt: "2026-07-29 10:30",
    sections: [
      {
        id: "sec-a",
        name: "A. Суурь үйлдэл",
        description: "Хялбар болон дунд түвшний бодлогууд.",
        selectedQuestionIds: ["qb-001", "qb-002", "qb-004"],
        randomPickCount: 2,
        pointsPerQuestion: 2,
        durationMinutes: 8,
        strategy: "random",
      },
      {
        id: "sec-b",
        name: "B. Нөхцөлт хэрэглээ",
        description: "Хэрэглэх болон шинжлэх түвшний даалгаврууд.",
        selectedQuestionIds: ["qb-001", "qb-003", "qb-004"],
        randomPickCount: 2,
        pointsPerQuestion: 3,
        durationMinutes: 16,
        strategy: "difficulty_balanced",
      },
    ],
  },
];

export const mockQuizzes: Quiz[] = [
  {
    id: "quiz-fractions-july",
    title: "Бутархайн суурь чадвар - 7 сарын тест",
    blueprintId: "bp-fractions-core",
    startAt: "2026-07-31 09:00",
    endAt: "2026-08-07 18:00",
    durationMinutes: 24,
    status: "scheduled",
    questionOverrides: [
      { questionId: "qb-001", mode: "mandatory" },
      { questionId: "qb-003", mode: "excluded" },
    ],
  },
];
