import type {
  BloomLevel,
  Blueprint,
  CompetencyType,
  DifficultyLevel,
  QuestionBankItem,
  QuestionType,
  QuestionWorkflowStatus,
  Quiz,
} from "./types";

export const mockAssignableUsers = [
  { id: "user-battuya", name: "Баттуя М.", email: "battuya@example.mn" },
  { id: "user-enkhbayar", name: "Энхбаяр Н.", email: "enkhbayar@example.mn" },
  { id: "user-baterdene", name: "Бат-Эрдэнэ Б.", email: "baterdene@example.mn" },
  { id: "user-sarantuya", name: "Сарантуя Д.", email: "sarantuya@example.mn" },
];

export const questionTypeLabels: Record<QuestionType, string> = {
  TRUE_FALSE: "Үнэн / худал",
  SINGLE_CHOICE: "Нэг сонголт",
  MULTIPLE_CHOICE: "Олон сонголт",
  ORDERING: "Эрэмбэлэх",
  MATCHING: "Харгалзуулах",  
  FILL_BLANK: "Нөхөх",
  NUMERIC: "Тоон хариулт",
  LIKERT: "Likert шкал",
  SJT: "SJT",
  MATRIX: "Матриц",
  SHORT_TEXT: "Богино хариулт",
  CASE_BUNDLE: "Кейсэд суурилсан багц",
  ESSAY: "Бичгийн шалгалт",
};

export const statusLabels: Record<QuestionWorkflowStatus, string> = {
  draft: "Ноорог",
  approval_requested: "Батлуулах хүсэлт",
  in_review: "Хянагдаж байна",
  changes_requested: "Засвар шаардлагатай",
  resubmitted: "Дахин батлуулах хүсэлт",
  approved: "Батлагдсан",
  published: "Нийтлэгдсэн",
  archived: "Архивлагдсан",
  rejected: "Татгалзсан",
  deleted: "Устгасан",
};

export const bloomLabels: Record<BloomLevel, string> = {
  remember: "Сэргээн санах",
  understand: "Ойлгох",
  apply: "Хэрэглэх",
  analyze: "Задлан шинжлэх",
  evaluate: "Үнэлэх",
  create: "Бүтээх",
};

export const competencyLabels: Record<CompetencyType, string> = {
  knowledge: "Мэдлэг",
  skill: "Ур чадвар",
  attitude: "Хандлага",
  digital: "Дижитал ур чадвар",
  professional: "Ажил мэргэжил",
};

export const difficultyLabels: Record<DifficultyLevel, string> = {
  very_easy: "Маш хялбар",
  easy: "Хялбар",
  medium: "Дунд",
  hard: "Хүнд",
  very_hard: "Маш хүнд",
};

export const topicTree = [
  { id: "algebra", label: "Шугаман алгебр" },
  { id: "fractions", label: "Энгийн бутархай" },
  { id: "communication", label: "Харилцааны ур чадвар" },
  { id: "cyber", label: "Кибер аюулгүй байдал" },
  { id: "leadership", label: "Манлайлал" },
];

const actor = {
  actorId: "mock-assessor",
  actorName: "Ассессор Б.",
  actorRole: "Assessor",
};

export const mockQuestionBank: QuestionBankItem[] = [
  {
    id: "qb-001",
    code: "MX-60",
    title: "Бутархайн тэнцүү байдал",
    body: "2/3 * 3/4 үйлдлийг гүйцэтгэхэд хамгийн хялбар хэлбэрт шилжүүлнэ үү.",
    type: "SINGLE_CHOICE",
    status: "published",
    defaultMaxScore: 2,
    defaultTimeSeconds: 60,
    bloomLevel: "apply",
    competencyType: "knowledge",
    topicId: "fractions",
    topicName: "Энгийн бутархай",
    difficulty: "easy",
    tags: ["бутархай", "үржих"],
    options: [
      { id: "a", label: "A", value: "1/2", isCorrect: true, score: 1 },
      { id: "b", label: "B", value: "6/12", score: 0 },
      { id: "c", label: "C", value: "8/9", score: 0 },
      { id: "d", label: "D", value: "5/7", score: 0 },
    ],
    answerKey: "A",
    rubric: "Зөв сонголт 2 оноо.",
    explanation: "2/3 болон 3/4-ийг үржүүлээд 6/12, хялбаршуулбал 1/2 болно.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-20 09:30",
    updatedAt: "2026-07-28 12:10",
    workflowHistory: [
      {
        id: "w-001",
        status: "published",
        comment: "Үндсэн тестийн санд нийтэлсэн.",
        createdAt: "2026-07-28 12:10",
        ...actor,
      },
    ],
  },
  {
    id: "qb-002",
    code: "MX-59",
    title: "Үйлдийн чанарыг ангилах",
    body: "a + b = b + a илэрхийлэл ямар хуультай тохирох вэ?",
    type: "MATCHING",
    status: "approved",
    defaultMaxScore: 3,
    defaultTimeSeconds: 90,
    bloomLevel: "understand",
    competencyType: "knowledge",
    topicId: "algebra",
    topicName: "Шугаман алгебр",
    difficulty: "medium",
    tags: ["хууль", "алгебр"],
    options: [
      { id: "a", label: "A", value: "Нэмэхийн байр солих хууль", isCorrect: true, score: 1 },
      { id: "b", label: "B", value: "Нэмэхийн бүлэглэх хууль", score: 0 },
      { id: "c", label: "C", value: "Үржихийн нэмэхэд тархах хууль", score: 0 },
    ],
    answerKey: "A",
    rubric: "Зөв харгалзуулалт бүр 1 оноо.",
    explanation: "Нэмэгдэхүүний байр солигдоход нийлбэр өөрчлөгдөхгүй.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Reviewer Т.",
    createdAt: "2026-07-19 11:00",
    updatedAt: "2026-07-27 16:20",
    workflowHistory: [
      {
        id: "w-002",
        status: "approved",
        comment: "Контент болон зөв хариулт баталгаажсан.",
        actorId: "mock-reviewer",
        actorName: "Reviewer Т.",
        actorRole: "Reviewer",
        createdAt: "2026-07-27 16:20",
      },
    ],
  },
  {
    id: "qb-003",
    code: "CS-21",
    title: "Харилцааны нөхцөл байдлын шийдвэр",
    body: "Иргэн бухимдсан үед хамгийн түрүүнд ямар хариу үйлдэл үзүүлэх вэ?",
    type: "SJT",
    status: "changes_requested",
    defaultMaxScore: 4,
    defaultTimeSeconds: 120,
    bloomLevel: "evaluate",
    competencyType: "attitude",
    topicId: "communication",
    topicName: "Харилцааны ур чадвар",
    difficulty: "hard",
    tags: ["SJT", "иргэн"],
    options: [
      { id: "a", label: "A", value: "Тайван сонсож, асуудлыг тодруулна.", score: 4 },
      { id: "b", label: "B", value: "Журам тайлбарлаад шууд дуусгана.", score: 1 },
      { id: "c", label: "C", value: "Дараагийн ажилтанд шилжүүлнэ.", score: 2 },
    ],
    answerKey: "A",
    rubric: "Нөхцөл байдлын оноо 1-4 хооронд.",
    explanation: "Эхний алхам нь сэтгэл хөдлөлийг намжаах сонсох үйлдэл байна.",
    media: [{ type: "audio", name: "Иргэний дуудлага.mp3", url: "#" }],
    createdBy: "Ассессор Б.",
    updatedBy: "Reviewer Т.",
    createdAt: "2026-07-18 10:00",
    updatedAt: "2026-07-26 15:30",
    workflowHistory: [
      {
        id: "w-003",
        status: "changes_requested",
        comment: "Хоёр дахь сонголтын онооны тайлбарыг тодруулах шаардлагатай.",
        actorId: "mock-reviewer",
        actorName: "Reviewer Т.",
        actorRole: "Reviewer",
        createdAt: "2026-07-26 15:30",
      },
    ],
  },
  {
    id: "qb-004",
    code: "DG-12",
    title: "Файлтай даалгавар",
    body: "Хавсаргасан хүснэгтийг уншаад хамгийн эрсдэлтэй үзүүлэлтийг тайлбарлана уу.",
    type: "ESSAY",
    status: "draft",
    defaultMaxScore: 5,
    defaultTimeSeconds: 300,
    bloomLevel: "analyze",
    competencyType: "digital",
    topicId: "cyber",
    topicName: "Кибер аюулгүй байдал",
    difficulty: "medium",
    tags: ["файл", "шинжилгээ"],
    options: [],
    answerKey: "Rubric based",
    rubric: "Асуудал тодорхойлох 2, нотолгоо 2, зөвлөмж 1.",
    explanation: "Өгөгдөл дээр тулгуурласан тайлбар шаардлагатай.",
    media: [{ type: "file", name: "risk-matrix.xlsx", url: "#" }],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-25 09:00",
    updatedAt: "2026-07-25 09:00",
    workflowHistory: [
      {
        id: "w-004",
        status: "draft",
        comment: "Эхний ноорог үүсгэсэн.",
        createdAt: "2026-07-25 09:00",
        ...actor,
      },
    ],
  },
  {
    id: "qb-005",
    code: "MX-58",
    title: "Рационал илэрхийлэл хялбарчлах",
    body:
      "Дараах илэрхийллийг хялбарчил: $\\frac{x-1}{x^2-1}=?$\n\n|№|асуулт|\n|---|---|\n|1|Хуваарийг үржигдэхүүн болгон задла.|\n|2|Ижил үржигдэхүүнийг хураа.|",
    type: "MULTIPLE_CHOICE",
    status: "published",
    defaultMaxScore: 3,
    defaultTimeSeconds: 90,
    bloomLevel: "apply",
    competencyType: "knowledge",
    topicId: "algebra",
    topicName: "Шугаман алгебр",
    difficulty: "medium",
    tags: ["олон сонголт", "томъёо"],
    options: [
      { id: "a", label: "A", value: "$\\frac{1}{x+1}$", isCorrect: true, score: 1 },
      { id: "b", label: "B", value: "$\\frac{1}{x-1}$", score: 0 },
      { id: "c", label: "C", value: "$x-1$", score: 0 },
      { id: "d", label: "D", value: "$x+1$", score: 0 },
    ],
    answerKey: "A",
    rubric: "Зөв хялбаршуулсан хэлбэр 3 оноо.",
    explanation: "$x^2-1=(x-1)(x+1)$ тул $x-1$ хураагдаж $\\frac{1}{x+1}$ үлдэнэ.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-25 10:00",
    updatedAt: "2026-07-29 10:00",
    workflowHistory: [
      {
        id: "w-005",
        status: "published",
        comment: "KaTeX томъёотой олон сонголтын жишээ нэмсэн.",
        createdAt: "2026-07-29 10:00",
        ...actor,
      },
    ],
  },
  {
    id: "qb-006",
    code: "OR-21",
    title: "Бутархайг өсөхөөр эрэмбэлэх",
    body: "Дараах бутархайнуудыг багаас их рүү зөв дарааллаар байрлуул.",
    type: "ORDERING",
    status: "approved",
    defaultMaxScore: 4,
    defaultTimeSeconds: 120,
    bloomLevel: "analyze",
    competencyType: "knowledge",
    topicId: "fractions",
    topicName: "Энгийн бутархай",
    difficulty: "medium",
    tags: ["эрэмбэлэх", "бутархай"],
    options: [
      { id: "a", label: "1", value: "1/8", score: 0 },
      { id: "b", label: "2", value: "1/4", score: 0 },
      { id: "c", label: "3", value: "1/2", score: 0 },
      { id: "d", label: "4", value: "3/4", score: 0 },
    ],
    answerKey: "1/8 → 1/4 → 1/2 → 3/4",
    rubric: "Бүрэн зөв дараалал 4 оноо.",
    explanation: "Ижил хуваарьт шилжүүлж харьцуулбал дараалал тодорхой болно.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Reviewer Т.",
    createdAt: "2026-07-22 14:00",
    updatedAt: "2026-07-27 09:15",
    workflowHistory: [
      {
        id: "w-006",
        status: "approved",
        comment: "Эрэмбэлэх даалгавар батлагдсан.",
        actorId: "mock-reviewer",
        actorName: "Reviewer Т.",
        actorRole: "Reviewer",
        createdAt: "2026-07-27 09:15",
      },
    ],
  },
  {
    id: "qb-007",
    code: "FI-50",
    title: "Хоосон зай нөхөх",
    body: "3/5 бутархайг хуваарь нь 15 байх бутархай болгон өргөтгөвөл хүртвэр нь ___ болно.",
    type: "FILL_BLANK",
    status: "approval_requested",
    defaultMaxScore: 3,
    defaultTimeSeconds: 90,
    bloomLevel: "apply",
    competencyType: "knowledge",
    topicId: "fractions",
    topicName: "Энгийн бутархай",
    difficulty: "easy",
    tags: ["нөхөх", "бутархай"],
    options: [],
    answerKey: "9",
    rubric: "Зөв тоон утга 3 оноо.",
    explanation: "Хуваарийг 15 болгохын тулд 5-ыг 3-аар үржүүлнэ, хүртвэрийг мөн 3-аар үржүүлнэ.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-23 11:20",
    updatedAt: "2026-07-28 11:20",
    workflowHistory: [
      {
        id: "w-007",
        status: "approval_requested",
        comment: "Батлуулах хүсэлт илгээсэн.",
        createdAt: "2026-07-28 11:20",
        ...actor,
      },
    ],
  },
  {
    id: "qb-008",
    code: "MT-14",
    title: "Аравтын ба энгийн бутархайг харьцуулах",
    body: "Дараах хосууд хоорондоо тэнцүү эсэхийг тэмдэглэ.",
    type: "MATRIX",
    status: "in_review",
    defaultMaxScore: 3,
    defaultTimeSeconds: 120,
    bloomLevel: "understand",
    competencyType: "knowledge",
    topicId: "fractions",
    topicName: "Энгийн бутархай",
    difficulty: "medium",
    tags: ["матриц", "харьцуулах"],
    options: [
      { id: "a", label: "3/10 ба 0.3", value: "Тэнцүү", isCorrect: true, score: 1 },
      { id: "b", label: "1/4 ба 0.25", value: "Тэнцүү", isCorrect: true, score: 1 },
      { id: "c", label: "2/5 ба 0.45", value: "Тэнцүү биш", isCorrect: true, score: 1 },
    ],
    answerKey: "Тэнцүү, тэнцүү, тэнцүү биш",
    rubric: "Мөр бүр 1 оноо.",
    explanation: "Энгийн бутархайг аравтын бутархайд шилжүүлж шалгана.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Reviewer Т.",
    createdAt: "2026-07-24 09:45",
    updatedAt: "2026-07-29 09:45",
    workflowHistory: [
      {
        id: "w-008",
        status: "in_review",
        comment: "Матриц даалгаврыг reviewer шалгаж байна.",
        actorId: "mock-reviewer",
        actorName: "Reviewer Т.",
        actorRole: "Reviewer",
        createdAt: "2026-07-29 09:45",
      },
    ],
  },
  {
    id: "qb-009",
    code: "NM-07",
    title: "Тоон хариулт",
    body: "$12 \\div 0.5$ үйлдлийн утгыг тоогоор бич.",
    type: "NUMERIC",
    status: "draft",
    defaultMaxScore: 2,
    defaultTimeSeconds: 60,
    bloomLevel: "remember",
    competencyType: "knowledge",
    topicId: "algebra",
    topicName: "Шугаман алгебр",
    difficulty: "very_easy",
    tags: ["тоон хариулт", "katex"],
    options: [],
    answerKey: "24",
    rubric: "Зөв тоон утга 2 оноо.",
    explanation: "0.5-аар хуваах нь 2-оор үржүүлэхтэй адил.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-26 08:30",
    updatedAt: "2026-07-26 08:30",
    workflowHistory: [
      {
        id: "w-009",
        status: "draft",
        comment: "Тоон хариултын ноорог.",
        createdAt: "2026-07-26 08:30",
        ...actor,
      },
    ],
  },
  {
    id: "qb-010",
    code: "LK-03",
    title: "Суралцах хандлагын Likert шкал",
    body: "Би шинэ мэдлэгийг өдөр тутмын ажилдаа хэрэглэхийг хичээдэг.",
    type: "LIKERT",
    status: "published",
    defaultMaxScore: 5,
    defaultTimeSeconds: 45,
    bloomLevel: "evaluate",
    competencyType: "attitude",
    topicId: "communication",
    topicName: "Харилцааны ур чадвар",
    difficulty: "easy",
    tags: ["likert", "хандлага"],
    options: [
      { id: "a", label: "1", value: "Огт санал нийлэхгүй", score: 0 },
      { id: "b", label: "2", value: "Санал нийлэхгүй", score: 0 },
      { id: "c", label: "3", value: "Дунд зэрэг", score: 0 },
      { id: "d", label: "4", value: "Санал нийлнэ", score: 0 },
      { id: "e", label: "5", value: "Бүрэн санал нийлнэ", isCorrect: true, score: 1 },
    ],
    answerKey: "1-5 шкал",
    rubric: "Likert шкалын оноолол 1-5.",
    explanation: "Хандлагын үнэлгээнд зөв/буруу бус шкалын оноо хэрэглэнэ.",
    media: [],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-21 13:00",
    updatedAt: "2026-07-30 13:00",
    workflowHistory: [
      {
        id: "w-010",
        status: "published",
        comment: "Likert шкал нийтлэгдсэн.",
        createdAt: "2026-07-30 13:00",
        ...actor,
      },
    ],
  },
  {
    id: "qb-011",
    code: "CB-09",
    title: "Кейсэд суурилсан багц",
    body: "Доорх байгууллагын сургалтын кейсийг уншаад дараах дэд асуултуудад хариул.",
    type: "CASE_BUNDLE",
    status: "archived",
    defaultMaxScore: 8,
    defaultTimeSeconds: 480,
    bloomLevel: "analyze",
    competencyType: "professional",
    topicId: "leadership",
    topicName: "Манлайлал",
    difficulty: "hard",
    tags: ["кейс", "манлайлал"],
    options: [
      { id: "a", label: "Дэд асуулт 1", value: "Гол эрсдэлийг тодорхойл.", score: 0 },
      { id: "b", label: "Дэд асуулт 2", value: "Сайжруулах эхний алхмыг сонго.", score: 0 },
      { id: "c", label: "Дэд асуулт 3", value: "Хэрэгжилтийн шалгуур үзүүлэлт бич.", score: 0 },
    ],
    answerKey: "Rubric based bundle",
    rubric: "Кейс ойлголт 3, шийдэл 3, хэмжүүр 2.",
    explanation: "Кейсийн нотолгоонд тулгуурласан хариулт шаардлагатай.",
    media: [{ type: "video", name: "case-brief.mp4", url: "#" }],
    createdBy: "Ассессор Б.",
    updatedBy: "Ассессор Б.",
    createdAt: "2026-07-15 16:00",
    updatedAt: "2026-07-25 16:00",
    workflowHistory: [
      {
        id: "w-011",
        status: "archived",
        comment: "Хуучин кейсийн хувилбарыг архивлав.",
        createdAt: "2026-07-25 16:00",
        ...actor,
      },
    ],
  },
];

export const mockBlueprints: Blueprint[] = [
  {
    id: "bp-fractions-core",
    title: "Бутархайн суурь чадвар",
    description: "Энгийн бутархайн ойлголт, үйлдэл, хэрэглээний тэнцвэртэй blueprint.",
    topicId: "fractions",
    topicName: "Энгийн бутархай",
    passScore: 73,
    totalDurationMinutes: 24,
    status: "ready",
    updatedAt: "2026-07-29 10:30",
    sections: [
      {
        id: "sec-a",
        name: "A. Суурь үйлдэл",
        description: "Хялбар болон дунд түвшний бодлогууд.",
        selectedQuestionIds: ["qb-001", "qb-002", "qb-004"],
        randomPickCount: 2,
        pointsPerQuestion: 2,
        durationMinutes: 8,
        strategy: "random",
      },
      {
        id: "sec-b",
        name: "B. Нөхцөлт хэрэглээ",
        description: "Хэрэглэх болон шинжлэх түвшний даалгаврууд.",
        selectedQuestionIds: ["qb-001", "qb-003", "qb-004"],
        randomPickCount: 2,
        pointsPerQuestion: 3,
        durationMinutes: 16,
        strategy: "difficulty_balanced",
      },
    ],
  },
];

export const mockQuizzes: Quiz[] = [
  {
    id: "quiz-fractions-july",
    title: "Бутархайн суурь чадвар - 7 сарын тест",
    blueprintId: "bp-fractions-core",
    priceMnt: 0,
    accessMode: "private_code",
    accessCode: "FRAC-2026",
    assignedUserIds: [],
    startAt: "2026-07-31 09:00",
    endAt: "2026-08-07 18:00",
    durationMinutes: 24,
    maxAttempts: 1,
    shuffleSections: false,
    shuffleAnswers: true,
    hideSolutions: true,
    showLeaderboard: false,
    showScore: true,
    showCorrectness: false,
    showCorrectAnswers: false,
    showExplanations: false,
    resultReleaseMode: "after_close",
    status: "scheduled",
    questionOverrides: [
      { questionId: "qb-001", mode: "mandatory" },
      { questionId: "qb-003", mode: "excluded" },
    ],
  },
];
