import type { CatalogAssessment, CatalogFilterOption } from "./types";

const now = Date.now();
const minutes = (value: number) => value * 60 * 1000;
const isoFromNow = (value: number) => new Date(now + minutes(value)).toISOString();

export const catalogAssessments: CatalogAssessment[] = [
  {
    id: "civil-servant-assessment",
    title: "Төрийн албан хаагчийн үнэлгээ",
    description:
      "Төрийн албан хаагчийн ёс зүй, эрх зүй, удирдлага, мэдээллийн технологи, сорил шалгалт.",
    category: "career",
    categoryLabel: "Ажил мэргэжил",
    accessType: "paid",
    accessLabel: "Төлбөртэй",
    durationMinutes: 120,
    questionCount: 80,
    price: 35000,
    language: "mn",
    badge: "popular",
    imageTone: "from-amber-50 to-amber-100",
    competencyTags: ["Төрийн албан хаагч", "Зрөнхий мэдлэг"],
    certificateAvailable: true,
    favorite: false,
    audienceTypeId: "audience-civil-servant",
    scheduledStartsAt: isoFromNow(20),
    scheduledEndsAt: isoFromNow(140),
    waitingRoomOpensAt: isoFromNow(5),
    totalPoints: 100,
    passingPercent: 70,
  },
  {
    id: "student-math-9",
    title: "9-р ангийн сурагчийн математикийн мэдлэг шалгах",
    description:
      "Математик сэтгэлгээ, логик сэтгэлгээ, онолын мэдлэг ур чадвар",
    category: "knowledge",
    categoryLabel: "Мэдлэг",
    accessType: "free",
    accessLabel: "Төлбөргүй",
    durationMinutes: 120,
    questionCount: 80,
    price: 0,
    language: "mn",
    badge: "new",
    imageTone: "from-emerald-50 to-emerald-100",
    competencyTags: ["Сурагч", "9-р анги"],
    certificateAvailable: true,
    favorite: false,
    audienceTypeId: "audience-student",
    scheduledStartsAt: isoFromNow(30),
    scheduledEndsAt: isoFromNow(150),
    waitingRoomOpensAt: isoFromNow(10),
    totalPoints: 100,
    passingPercent: 60,
  },
  {
    id: "institutional-evaluation-2024",
    title: "Institutional Internal Evaluation — 2024",
    description:
      "Confidential diagnostic examination mapping operational efficiency and core competencies.",
    category: "career",
    categoryLabel: "Ажил мэргэжил",
    accessType: "targeted",
    accessLabel: "Зорилтот",
    durationMinutes: 60,
    questionCount: 40,
    price: 0,
    language: "en",
    badge: "targeted",
    imageTone: "from-blue-50 to-blue-100",
    competencyTags: ["Targeted", "Internal"],
    certificateAvailable: false,
    favorite: false,
    audienceTypeId: "audience-candidate",
    scheduledStartsAt: isoFromNow(40),
    scheduledEndsAt: isoFromNow(100),
    waitingRoomOpensAt: isoFromNow(25),
    totalPoints: 100,
    passingPercent: 50,
  },
  {
    id: "professional-it-certification",
    title: "Professional IT Certification Assessment",
    description:
      "Comprehensive assessment of technical skills, networking logic, and programming paradigms...",
    category: "digital",
    categoryLabel: "Дижитал ур чадвар",
    accessType: "paid",
    accessLabel: "Төлбөртэй",
    durationMinutes: 100,
    questionCount: 70,
    price: 30000,
    language: "en",
    badge: "popular",
    imageTone: "from-slate-50 to-slate-100",
    competencyTags: ["Professional", "IT"],
    certificateAvailable: true,
    favorite: false,
    audienceTypeId: "audience-candidate",
  },
  {
    id: "english-proficiency-toefl",
    title: "English Proficiency Assessment (TOEFL-MN)",
    description:
      "National language baseline standard checking listening, comprehensive syntax, and syntax...",
    category: "knowledge",
    categoryLabel: "Мэдлэг",
    accessType: "free",
    accessLabel: "Төлбөргүй",
    durationMinutes: 120,
    questionCount: 70,
    price: 25000,
    language: "en",
    badge: "new",
    imageTone: "from-emerald-50 to-emerald-100",
    competencyTags: ["Language", "English"],
    certificateAvailable: false,
    favorite: false,
    audienceTypeId: "audience-student",
  },
  {
    id: "special-skills-competency",
    title: "Special Skills Competency Assessment",
    description:
      "Exclusive skills-diagnostic mapping field readiness for security operations and protoc...",
    category: "skill",
    categoryLabel: "Ур чадвар",
    accessType: "targeted",
    accessLabel: "Зорилтот",
    durationMinutes: 60,
    questionCount: 30,
    price: 0,
    language: "en",
    badge: "targeted",
    imageTone: "from-blue-50 to-blue-100",
    competencyTags: ["Targeted", "Skills"],
    certificateAvailable: true,
    favorite: false,
    audienceTypeId: "audience-candidate",
  },
];

export const catalogCategories: CatalogFilterOption[] = [
  { id: "all", label: "Бүгд", count: 24 },
  { id: "knowledge", label: "Мэдлэг", count: 8 },
  { id: "skill", label: "Ур чадвар", count: 6 },
  { id: "attitude", label: "Хандлага", count: 2 },
  { id: "digital", label: "Дижитал ур чадвар", count: 4 },
  { id: "career", label: "Ажил мэргэжил", count: 4 },
];
