import type { CatalogAssessment, CatalogFilterOption } from "./types";

const now = Date.now();
const minutes = (value: number) => value * 60 * 1000;
const isoFromNow = (value: number) => new Date(now + minutes(value)).toISOString();

export const catalogAssessments: CatalogAssessment[] = [
  {
    id: "data-analysis-basic",
    title: "Мэдээллийн шинжилгээний үндэс",
    description:
      "Өгөгдөл цуглуулах, боловсруулах, дүн шинжилгээ хийх үндсэн мэдлэгийг үнэлнэ.",
    category: "knowledge",
    categoryLabel: "Мэдлэг",
    accessType: "free",
    accessLabel: "Төлбөргүй",
    durationMinutes: 45,
    questionCount: 60,
    price: 0,
    language: "mn",
    badge: "new",
    imageTone: "from-blue-50 to-indigo-100",
    competencyTags: ["Мэдлэг", "Дижитал ур чадвар"],
    certificateAvailable: true,
    favorite: true,
    scheduledStartsAt: isoFromNow(20),
    scheduledEndsAt: isoFromNow(65),
    waitingRoomOpensAt: isoFromNow(5),
    requiredEarlyJoinMinutes: 15,
    totalPoints: 100,
    passingPercent: 70,
  },
  {
    id: "communication-skill",
    title: "Харилцааны ур чадвар",
    description: "Асуулт сонсох, ойлгох, үр дүнтэй харилцах чадварыг үнэлнэ.",
    category: "skill",
    categoryLabel: "Ур чадвар",
    accessType: "paid",
    accessLabel: "Төлбөртэй",
    durationMinutes: 30,
    questionCount: 40,
    price: 25000,
    language: "mn",
    badge: "popular",
    imageTone: "from-orange-50 to-rose-100",
    competencyTags: ["Ур чадвар", "Хандлага"],
    certificateAvailable: false,
  },
  {
    id: "cyber-security-basic",
    title: "Кибер аюулгүй байдлын үндэс",
    description:
      "Кибер аюулгүй байдлын үндсэн ойлголт, эрсдэл, хамгаалалтын аргууд.",
    category: "digital",
    categoryLabel: "Дижитал ур чадвар",
    accessType: "paid",
    accessLabel: "Төлбөртэй",
    durationMinutes: 50,
    questionCount: 50,
    price: 25000,
    language: "mn",
    badge: "new",
    imageTone: "from-sky-50 to-cyan-100",
    competencyTags: ["Мэдлэг", "Дижитал ур чадвар"],
    certificateAvailable: true,
  },
  {
    id: "teamwork-skill",
    title: "Багаар ажиллах ур чадвар",
    description:
      "Багийн гишүүний үүрэг, хамтын ажиллагаа, итгэлцэл бий болгох чадвар.",
    category: "attitude",
    categoryLabel: "Хандлага",
    accessType: "timed",
    accessLabel: "Хугацаатай",
    durationMinutes: 35,
    questionCount: 35,
    price: 0,
    language: "mn",
    badge: "timed",
    imageTone: "from-pink-50 to-violet-100",
    competencyTags: ["Ур чадвар", "Хандлага"],
    certificateAvailable: false,
    scheduledStartsAt: isoFromNow(90),
    scheduledEndsAt: isoFromNow(125),
    waitingRoomOpensAt: isoFromNow(75),
    requiredEarlyJoinMinutes: 15,
    totalPoints: 80,
    passingPercent: 65,
  },
  {
    id: "teacher-standard",
    title: "Багшийн мэргэжлийн стандарт",
    description:
      "Багшийн ажлын байрны суурь чадамж, хичээл төлөвлөлт, үнэлгээний чадвар.",
    category: "career",
    categoryLabel: "Ажил мэргэжил",
    accessType: "paid",
    accessLabel: "Төлбөртэй",
    durationMinutes: 60,
    questionCount: 70,
    price: 30000,
    language: "mn",
    badge: "targeted",
    imageTone: "from-violet-50 to-purple-100",
    competencyTags: ["Мэдлэг", "Мэргэжил"],
    certificateAvailable: true,
  },
  {
    id: "leadership-organisation",
    title: "Компанийн манлайллын үнэлгээ",
    description:
      "Байгууллагын захиалгаар тохируулсан манлайлал, шийдвэр гаргалтын үнэлгээ.",
    category: "skill",
    categoryLabel: "Ур чадвар",
    accessType: "organisation",
    accessLabel: "Захиалгат үнэ",
    durationMinutes: 45,
    questionCount: 55,
    price: 0,
    language: "mn",
    badge: "organisation",
    imageTone: "from-indigo-50 to-blue-100",
    competencyTags: ["Ур чадвар", "Хандлага"],
    organisation: "Demo Organisation",
    certificateAvailable: true,
  },
  {
    id: "english-basic",
    title: "Англи хэлний суурь мэдлэг",
    description: "Унших, сонсох, үгийн сан, дүрмийн суурь чадварыг үнэлнэ.",
    category: "knowledge",
    categoryLabel: "Мэдлэг",
    accessType: "free",
    accessLabel: "Төлбөргүй",
    durationMinutes: 40,
    questionCount: 50,
    price: 0,
    language: "en",
    imageTone: "from-emerald-50 to-teal-100",
    competencyTags: ["Мэдлэг", "Хэл"],
    certificateAvailable: false,
    scheduledStartsAt: isoFromNow(-10),
    scheduledEndsAt: isoFromNow(30),
    waitingRoomOpensAt: isoFromNow(-25),
    requiredEarlyJoinMinutes: 15,
    totalPoints: 100,
    passingPercent: 60,
  },
  {
    id: "project-management",
    title: "Төслийн удирдлагын суурь",
    description:
      "Төслийн төлөвлөлт, эрсдэл, баг, хугацаа болон нөөцийн суурь ойлголт.",
    category: "career",
    categoryLabel: "Ажил мэргэжил",
    accessType: "paid",
    accessLabel: "Төлбөртэй",
    durationMinutes: 90,
    questionCount: 80,
    price: 60000,
    language: "mn",
    badge: "certificate",
    imageTone: "from-amber-50 to-yellow-100",
    competencyTags: ["Мэдлэг", "Ур чадвар"],
    certificateAvailable: true,
  },
];

export const catalogCategories: CatalogFilterOption[] = [
  { id: "all", label: "Бүгд", count: 512 },
  { id: "knowledge", label: "Мэдлэг", count: 128 },
  { id: "skill", label: "Ур чадвар", count: 156 },
  { id: "attitude", label: "Хандлага", count: 64 },
  { id: "digital", label: "Дижитал ур чадвар", count: 98 },
  { id: "career", label: "Ажил мэргэжил", count: 66 },
  { id: "other", label: "Бусад", count: 32 },
];
